# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mensajerechazo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mensajerechazo(object):
    def setupUi(self, mensajerechazo):
        mensajerechazo.setObjectName("mensajerechazo")
        mensajerechazo.resize(433, 276)
        mensajerechazo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(158, 158, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.centralwidget = QtWidgets.QWidget(mensajerechazo)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 110, 301, 31))
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        mensajerechazo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mensajerechazo)
        self.statusbar.setObjectName("statusbar")
        mensajerechazo.setStatusBar(self.statusbar)

        self.retranslateUi(mensajerechazo)
        QtCore.QMetaObject.connectSlotsByName(mensajerechazo)

    def retranslateUi(self, mensajerechazo):
        _translate = QtCore.QCoreApplication.translate
        mensajerechazo.setWindowTitle(_translate("mensajerechazo", "MainWindow"))
        self.label.setText(_translate("mensajerechazo", "EL PEDIDO HA SIDO RECHAZADO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mensajerechazo = QtWidgets.QMainWindow()
    ui = Ui_mensajerechazo()
    ui.setupUi(mensajerechazo)
    mensajerechazo.show()
    sys.exit(app.exec_())
